name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set up kubectl
        uses: azure/aks-set-context@v3
        with:
          resource-group: enexis-lab-rg
          cluster-name: enexis-lab-aks

      - name: Build and Push Docker Image
        run: |
          az acr login --name enexislabacr123
          docker build -t enexislabacr123.azurecr.io/enexis-microservice:${{ github.sha }} .
          docker push enexislabacr123.azurecr.io/enexis-microservice:${{ github.sha }}

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/enexis-microservice enexis-microservice=enexislabacr123.azurecr.io/enexis-microservice:${{ github.sha }}
          kubectl rollout status deployment/enexis-microservice
